### ISSUE TITLE
Potential Memory Leak in 0.20.15

### ISSUE THREAD

**Issue by tawmaz** [pocketnetteam/pocketnet.core#112]
A potential memory leak has been reported in version 0.20.x running under Linux.  Creating this issue for tracking of valgrind test results and which modules are using the most memory.

**Comment by dmaltsiniotis** [comment]
Would this manifest itself by the debug log reporting an out of memory exception, and the process exiting, even though the host OS has plenty of available memory? I've seen that a few times so far, but have yet to reproduce it on on 0.20.15.

**Comment by andyoknen** [comment]
@dmaltsiniotis The `out of memory` message does not indicate a lack of memory, but rather an error in the code when inaccessible memory is accessed.

**Comment by the-real-vortex-v** [comment]
> Would this manifest itself by the debug log reporting an out of memory exception, and the process exiting, even though the host OS has plenty of available memory? I've seen that a few times so far, but have yet to reproduce it on on 0.20.15.

I think this is the issue that Mikkel was talking about. He's saying that he lets it run and after a day or so it goes to about 6gb to 9gb of ram.
My guess is a buggy library. I haven't seen this issue running on a devuan system updated to chimaera (current stable build). I'm seeing ~500mb to 800mb of usage when I drop sqlite to 50mb.

I'm compiling from source. What can I do to see if there's a problem when compiling on source?

**Comment by andyoknen** [comment]
@tawmaz Is there any progress on this task?

**Comment by tawmaz** [comment]
My own nodes on mainnet appear to be stable at 4.8GB virtual memory.  I ran Valgrind last week and it reported a lot of potential issues (>1400), but these are often memory which is not explicitly freed on program exit.  With a larger SQLite page cache the memory footprint did appear to increase over time probably due to each db instance having it's own cache.

**Comment by tawmaz** [comment]
Closing for now as my nodes appear to be stable after multiple weeks of operation at ~5GB virtual memory.
