### ISSUE TITLE
The program works, but the balance does not change

### ISSUE THREAD

**Issue by Linkdealer** [pocketnetteam/pocketnet.core#113]
The program works, transactions take place, but the balance does not change (0.000000000). Why? I heard that you first need to send money to the wallet account. This is true? Please give instructions on this.

**Comment by andyoknen** [comment]
How do you check the balance? Can you provide your address?

**Comment by Linkdealer** [comment]
> How do you check the balance? Can you provide your address?

I check ´the balance on overview tab:
https://yadi.sk/i/X9HDwrS6Rs7dvw

Adress: 
PJfw92FGJji3d4SSZoRoJEmE4MXLk3Z97y (from "Receiving addresses", right?)

**Comment by andyoknen** [comment]
@Linkdealer It looks like there are no coins behind this address. Did you transfer the conns to him?

**Comment by Linkdealer** [comment]
> @Linkdealer It looks like there are no coins behind this address. Did you transfer the conns to him?

no, I did not transfer money there. I can't find a description of how it works anywhere. There is no manual. I have to learn everything step by step from my own experience.

**Comment by andyoknen** [comment]
@Linkdealer 

You can start from here. Also feel free to ask further questions
https://github.com/pocketnetteam/pocketnet.core/tree/0.20/doc/help

**Comment by Linkdealer** [comment]
> @Linkdealer
> 
> You can start from here. Also feel free to ask further questions https://github.com/pocketnetteam/pocketnet.core/tree/0.20/doc/help

Thanks! I will study.
