### ISSUE TITLE
Implement a class to implement a WebSocket message queue.

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.core#119]
The class must have a thread-safe stack/queue. 
Message preparation and sending should be highlighted in the thread.
Creating and deleting WebSocket connections should be thread-safe.

**Comment by lostystyg** [comment]
Currently we are using boost::asio::strand for managing message queue. All actions with queue are performed inside strand wrapper which is guaranteed to be thread safe. (See [About Strands](https://www.boost.org/doc/libs/1_78_0/doc/html/boost_asio/overview/core/strands.html)).
E.x. adding message to queue:
```
strand.post([self, out_header, out_message, callback]() {
          self->send_queue.emplace_back(out_header, out_message, callback);
          if(self->send_queue.size() == 1)
            self->send_from_queue();
        });
```
Also all other actions with queue are performed inside async handlers that are wrapped by calling strand->wrap() method that guarantees that onl;y one async handler will be invoked in a time.

**Comment by andyoknen** [comment]
@lostystyg Could you take this to work?

**Comment by tawmaz** [comment]
Created pull request to fix segmentation fault and make accesses to WSConnections map thread safe: https://github.com/pocketnetteam/pocketnet.core/pull/129
As @lostystyg mentioned we are using asio for queueing so we should be good to go with this patch.  We may look at optimizing the lock mechanism in the future if it is found to be a bottleneck.

**Comment by andyoknen** [comment]
I propose to consider the implementation of this task for version 0.20.18

**Comment by lostystyg** [comment]
[Here](https://github.com/lostystyg/pocketnet.core/tree/fix/websocket) websocket queue processing is extracted to a different thread and works well with shallow-minded testing. I'll create a PR after 0.20.18 released because we are targeting these changes for 0.20.19
