### ISSUE TITLE
Implementation of the SQLite cache resizing parameter

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.core#120]
Implement a parameter to change the size of the SQLite connection cache at the job level, instead of compiling.
There should be two parameters - one for the main connection and one for read-only connections.
Define default values

**Comment by andyoknen** [comment]
@tawmaz Is there any progress on this task?

**Comment by tawmaz** [comment]
Pull request: https://github.com/pocketnetteam/pocketnet.core/pull/151

**Comment by andyoknen** [comment]
In release 0.20.18, the parameters are disabled due to problems starting a node with an existing database - additional research is needed on this
https://github.com/pocketnetteam/pocketnet.core/blob/46fcd72b7810775027b0298af7321d461f88b4f1/src/pocketdb/SQLiteDatabase.cpp#L174

I was also experiencing problems with the sqlsharedcache argument
https://github.com/pocketnetteam/pocketnet.core/blob/46fcd72b7810775027b0298af7321d461f88b4f1/src/pocketdb/SQLiteDatabase.cpp#L141
