### ISSUE TITLE
ErrorLogCallback

### ISSUE THREAD

**Issue by davkastheranger19** [pocketnetteam/pocketnet.core#123]
I'm running linux server 20.04.
24GB Ram
8 VCore CPU
Running version node v0.20.16

2021-12-21T19:10:20Z ErrorLogCallback: 1; Message: statement aborts at 16: [
            select
                t.Id

            from web.Content f

            join web.ContentMap fm on fm.ROWID = f.ROWID

            cross join Transactions t indexed by Tra
2021-12-21T19:10:21Z ErrorLogCallback: 1; Message: statement aborts at 16: [
            select
                t.Id

            from web.Content f

            join web.ContentMap fm on fm.ROWID = f.ROWID

            cross join Transactions t indexed by Tra

**Comment by andyoknen** [comment]
Thank you for your response. It looks like the errors of the search query in the sqlite database. We are dealing with this issue.

**Comment by davkastheranger19** [comment]
> Thank you for your response. It looks like the errors of the search query in the sqlite database. We are dealing with this issue.

I've been shutting down the pocketcoind service and restarting it when I see this error. Should I continue to do that, or does it matter?

**Comment by dmaltsiniotis** [comment]
> > Thank you for your response. It looks like the errors of the search query in the sqlite database. We are dealing with this issue.
> 
> I've been shutting down the pockcoind service and restarting it when I see this error. Should I continue to do that, or does it matter?

I operate a node and I would suggest not do that. These kinds of timeout errors are transient in nature, and resolve themselves usually. They aren't critical errors. If you are seeing huge amounts of timeouts though, it may be worth investigating the speed of the hard disk that the process is running on, and possibly upgrading to a faster disk.

**Comment by davkastheranger19** [comment]
I'm running it on a VM that is sitting on 3 NVMe drives in raid, so it doesn't get much faster than what I've got at the consumer level.
I'll leave it be unless I see that nodes peers are timing out. Thanks.

**Comment by andyoknen** [comment]
As XXX rightly noted, these errors are uncritical and do not require any action, as long as their number remains small.

**Comment by andyoknen** [comment]
I will close this question and create an issue to optimize these SQL queries - https://github.com/pocketnetteam/pocketnet.core/issues/125
