### ISSUE TITLE
The balance does not increase

### ISSUE THREAD

**Issue by Linkdealer** [pocketnetteam/pocketnet.core#128]
Continued topic https://github.com/pocketnetteam/pocketnet.core/issues/113

The balance does not increase: https://disk.yandex.ru/i/8gujHKa7CNbiVA

As you can see in the picture, 50 PKOINs were added to the balance almost a week ago. And there hasn't been a single increase in balance since then.

Here you can see that the program processes transactions: https://disk.yandex.ru/i/X9k8LJkWepfRnQ

But coins are not credited for this at all. Do I understand correctly that by making these transactions the program should receive a plus to the balance? For example, I have conducted 100 transactions, added 0, 00000000003 PKOIN, and the balance increased to 50.00000000003 PKOIN? 

Explain to me how this should work in practice.

**Comment by dmaltsiniotis** [comment]
Hi @Linkdealer,

I'm going to try to understand what you're asking, but it's a little difficult. To answer your question: 

> Do I understand correctly that by making these transactions the program should receive a plus to the balance?

No, this is not a correct understanding. Those transactions in the mempool have no effect on your PKOIN balance.

I'm going to assume that your goal is earn PKOIN by running a Pocketcoin node. You have correctly figured out that you need at least 50 PKOIN in your wallet balance to start the process of "staking". However, there are many other considerations here that will affect how often you are able to "win" staking events. "Winning a stake" is what makes your balance go up. Currently, each staking event yields approximately 5 PKOIN.

A major factor in how often you "win" these staking events, is how much PKOIN you have in your staking wallet. If you only stake the minimum amount, 50 PKOIN, it could take up to 4 weeks or more before you win your first staking event. If you were to have for example, ~2700 PKOIN staked, you would win a staking event approximately once per day on average.

How often you win a staking event, is directly proportional to how much you have staked, and the total or "Net staked weight" of the network. Put another way: The more PKOIN'S that are staked on the whole network, the less chance you have of winning a staking event. The reverse is also true.

You can see an estimate of how long it will take to win a staking event by going to the console area of the GUI and issuing the following command: `getstakinginfo`. This will result in an output similar to this:

```
{
  "enabled": true,
  "staking": true,
  "errors": "",
  "currentblockweight": 21768,
  "currentblocktx": 16,
  "difficulty": 216076.2357790906,
  "search-interval": 16,
  "weight": 82016290389,
  "netstakeweight": 239310048602422,
  "expectedtime": 437675
}
```
From this output, you must ensure that `enabled`, and `staking` are **both set to true**, and that there are no errors. Additionally, look at the expected time, this number is the seconds estimated between staking events. In my case, it's 437675 seconds / 60 seconds in minute / 60 minutes in a hour / 24 hours in a day = 5.06 days. This is the time I can expect, on average, to see my balance go up by 5 PKOIN if my node is properly set up for staking.

Another command you can run to see if your node has ever staked is: `getstakereport`. This will give you a report/table of every staking event your wallet has, if any.

I hope this helps,

-Demetri

**Comment by Linkdealer** [comment]
> I hope this helps,
> 
> -Demetri

Thanks a lot for your detailed answer. You understood my question absolutely correctly. If I understood everything correctly, then this is a win-win lottery with 24% per annum. Minus possible risks, costs for electricity, depreciation of equipment and operator's working hours ... The terms "win" are badly associated with business :) But now I understand what this is about. Thank you again!
