### ISSUE TITLE
Crash on exit with server=0

### ISSUE THREAD

**Issue by lostystyg** [pocketnetteam/pocketnet.core#135]
How to reproduce: Ctrl+c after successful startup with -server=0
This is the result of creating g_socket variable [only if](https://github.com/pocketnetteam/pocketnet.core/blob/2ac0ef32fe1da86f983896bc38b19664d77e707c/src/init.cpp#L1743)  -server=1 [here](https://github.com/pocketnetteam/pocketnet.core/blob/2ac0ef32fe1da86f983896bc38b19664d77e707c/src/httpserver.cpp#L441) but g_socket is null [here](https://github.com/pocketnetteam/pocketnet.core/blob/2ac0ef32fe1da86f983896bc38b19664d77e707c/src/httprpc.cpp#L185). Need at least add checking for null and probably rework a bit shutdown process

**Comment by lostystyg** [comment]
Also probably just remove -server argument because it seems -listen does the same job. But need check if it is.

**Comment by lostystyg** [comment]
-server is irrelevant to -listen option. -server affects rpc socket's stuff, while -listen affects socket that is used to establish connection between nodes.

**Comment by andyoknen** [comment]
@lostystyg  What exactly is affected by -server?

**Comment by lostystyg** [comment]
> @lostystyg What exactly is affected by -server?

Sockets in httpserver and httprpc that used for rpc http requests. Setting -server=0 means node will not accept any http requests to it but will still sync chain with other nodes. 

-listen=0 affects sockets in net.cpp and prevents connecting other nodes to it (e.x. another node wouldn't been able to connect to our node and download blocks from us). But we still can connect to other nodes in one-way (to download blocks e.x.) and process rpc requests

**Comment by lostystyg** [comment]
#165 is a hot fix and i consider close this after PR merged and open a new issue for 0.21.0 milestone for refactoring socket access by probably introducing some interface and use dummy in case of -server=0 like it is analogically done in wallet if wallet is disabled. This would be necessary because rpc sockets are accessed in more places in 0.21 version and there are some problems with current socket usage, e.x. [here](https://github.com/lostystyg/pocketnet.core/blob/cfeb54c98d81cab04705e3643ab9b53b73de350b/src/interfaces/chain.cpp#L129) so it is better to do this in some sort of generalized manner instead of make a check in every place and control it manually. Also there is a lot of work done by bitcoin to left global variables and use node context so i think it would be better to use rpc sockets in the same manner and it is another point for a small refactoring this.

**Comment by lostystyg** [comment]
Furthermore, probably linked [place](https://github.com/lostystyg/pocketnet.core/blob/cfeb54c98d81cab04705e3643ab9b53b73de350b/src/interfaces/chain.cpp#L129) has a redundant logic that can be avoided but still this is related to rpc socket usage so i think this need an additional discussion and suggest do this in a separate issue for 0.21
