### ISSUE TITLE
Automation of assembly and unit testing

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.core#139]
Implement the processes of automatic assembly and launch of unit tests for branch 0.20 with a trigger for pull request

**Comment by tawmaz** [comment]
I am looking at how to do this with GitHub actions.  AWS CodeBuild is another option I am very familiar with and can use github as a repository as a fallback.

**Comment by tawmaz** [comment]
I have a github actions yaml file created in my repo which complete make + make check + make deploy: https://github.com/tawmaz/pocketnet.core/blob/master/.github/workflows/makecheck.yml
Here is a test run against the old reindexer build: https://github.com/tawmaz/pocketnet.core/runs/4723888680?check_suite_focus=true
It needs a few tweaks to upload the resultant file and speed up the build.  Right now it takes about an hour to complete.

**Comment by andyoknen** [comment]
[![make check](https://github.com/tawmaz/pocketnet.core/actions/workflows/makecheck.yml/badge.svg)](https://github.com/tawmaz/pocketnet.core/actions/workflows/makecheck.yml)

**Comment by tawmaz** [comment]
https://github.com/pocketnetteam/pocketnet.core/pull/141

**Comment by tawmaz** [comment]
Here is the first successful automated build + testrun for the pocketnet.core repo: https://github.com/pocketnetteam/pocketnet.core/actions/runs/1681403579
It will run automatically for pull requests and can also be invoked manually through the Actions tab.
