### ISSUE TITLE
Reducing -MaxConnection from 1000 to 865 because of system limitations.

### ISSUE THREAD

**Issue by davkastheranger19** [pocketnetteam/pocketnet.core#14]
**Describe the bug**
Reducing -MaxConnection from 1000 to 865 because of system limitations.

**To Reproduce**
Have config set -MaxConnection to 1000
Have system with 12GB Ram 8 Cores
Running as VM ubuntu server 20.04

Since this is a VM, I could allocate more resources to the VM, but I don't see any documentation on why the max connections is reduced and what its calculations are based on.
What can I do (if it makes sense) to increase the max connections?

**Comment by andyoknen** [comment]
What kind of connections are you talking about?

**Comment by pocketnetteam** [comment]
> Inside of the pocketcoin.config you can set maxconnections=XXXX

I meant what kind of connections are you talking about? Web socket, http or ... ?
