### ISSUE TITLE
Installation Manager

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.core#145]
We need an easy installation manager for Pocketnet & Bastion software.
The size of the final installer should strive to the minimum for distribution via the Pocketnet blockchain as part of the transaction payload.

It is assumed that the source codes will be located in the public repository of the PocketnetTeam account.

In the blockchain, a cross-reference to the published tag in GitHub will be implemented in the Post transaction (later allocated to a separate type of Release transaction).

**Comment by andyoknen** [comment]
Realize GET link for txHash with Post with Binary of installation manager over REST http socket

https://github.com/pocketnetteam/pocketnet.core/blob/0.20/src/rest.cpp

**Comment by tawmaz** [comment]
It would be nice if this also placed the checkpoints/main.sqlite3 file in the correct directory as well.

**Comment by andyoknen** [comment]
@tawmaz As for the checkpoint file, we need to change the path to it so that it is not in the data directory, but together with the binary file. But this can cause problems in linux, since binary files are installed in /usr/local/bin
