### ISSUE TITLE
Imported Mempool transactions from disk failed

### ISSUE THREAD

**Issue by davkastheranger19** [pocketnetteam/pocketnet.core#15]
**Describe the bug**
Running Node on Ubuntu 20.04 and I start the server by issuing the command pocketcoind
If I need to reboot the VM or the host, I press ctrl + c to shutdown the pocketcoind app. Once it says it's done shutting down, I reboot and then reopen the VM and reissue the pocketcoind command. During the startup process, one of the steps is "Imported Mempool transactions from disk" This fails every time, even though during the shutdown process it says it wrote them to disk successfully.

**Comment by andyoknen** [comment]
We are working on optimizing the work with the mempool. In any case, this is not a critical problem, since it is assumed that the nodes will not be overloaded often.

**Comment by davkastheranger19** [comment]
> We are working on optimizing the work with the mempool. In any case, this is not a critical problem, since it is assumed that the nodes will not be overloaded often.

Ok. I will ignore for now.
Thanks
