### ISSUE TITLE
Benchmark testing

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.core#161]
The main idea is to prerelease benchmark tests to identify the regression of speed.
Bitcoin has a benchmark logic, we could adapt it to our needs, if necessary.
First we need to try to run the current implementation and look at the results to decide on additional improvements. 
I suggest placing the results in this issue

**Comment by tawmaz** [comment]
I am targeting the end of this week to have a pull request with at least the blockassemble bench test working, so potentially this could be in 0.20.18.
