### ISSUE TITLE
Request to add an IP address to the source code

### ISSUE THREAD

**Issue by ghost** [pocketnetteam/pocketnet.core#194]
This issue is a template for a request to add an IP address to the source code of the node. This is necessary to maintain and expand the network so that new nodes can connect to the network using the maximum number of peers. 

The current list of nodes can be seen in the file https://github.com/pocketnetteam/pocketnet.core/blob/0.20/contrib/seeds/nodes_main.txt

Please fill in the fields below to review the request:

IPv4 Address (e.g. 127.0.0.1): ... 
IPv6 Address (If available): ...
Public HTTP API Port: 38081 (default)
Public WS API Port: 8087 (default)

**I confirm that my node is available at the specified addresses and ports 24/7**

**Comment by gf110** [comment]
also please add 178.217.159.221 and 178.217.159.227

**Comment by andyoknen** [comment]
@gf110 Did you close the issue because it is irrelevant?

**Comment by ghost** [comment]
I'm sorry, I'm just learning how to use github

**Comment by ghost** [comment]
good day! it seems that I submitted my request incorrectly - it is indicated on top in the example.
IPv4-адрес (например, 127.0.0.1): ... 178.217.159.219 и 178.217.159.221 и 178.217.159.227
I edited the example as it was. Please add the following IP addresses to the list 178.217.159.219 и 178.217.159.221 и 178.217.159.227

**Comment by andyoknen** [comment]
OK, we will add you to the next release

**Comment by ghost** [comment]
another user gave the go-ahead to add his ip to the list. 46.175.122.243
Unfortunately, not all users are friends with github, so I will ask people who will give consent, I will write here.

**Comment by ghost** [comment]
Please add the following ip addresses:-46.175.123.77 & 178.217.155.168 & 178.217.155.169 & 178.217.155.170

**Comment by HiHat** [comment]
> another user gave the go-ahead to add his ip to the list. 46.175.122.243 Unfortunately, not all users are friends with github, so I will ask people who will give consent, I will write here.

@gf110, please notify owner of 46.175.122.243 node about required update to 0.20.26 (currently it have 0.20.19)
