### ISSUE TITLE
Limiting the characters of account names

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.core#207]
It is necessary to prohibit any spaces in the name, non-printable characters (%*&$^#, etc.)

Allow next symbols:
abcdefghijklmnopqrstuvwxyz0123456789_

**Comment by tawmaz** [comment]
Here is an example account: https://bastyon.com/PWGtSLjQE9W4uu6vdrkMvxxXLvyqXDgj9M

**Comment by andyoknen** [comment]
#209
