### ISSUE TITLE
v 0.20.18 - Error: block timestamp too far in the future

### ISSUE THREAD

**Issue by Dylan-86** [pocketnetteam/pocketnet.core#213]
Hi,
I launch
`pocketcoind -listen=0 -blocksonly=1`

And at the end I get:
`2022-02-21T16:52:51Z ERROR: AcceptBlockHeader: Consensus::ContextualCheckBlockHeader: cf3a2df0292d8a85724a8e9e086f01a54fea53d8274b359c559a6a0c95a6a079, time-too-new, block timestamp too far in the future (code 16)
`

Ubuntu 21.10, latest version of pocketnet (0.20.18)

What's wrong?

My machine's current time is correct (EST timezone)

**Comment by andyoknen** [comment]
@Dylan-86 The block looks ordinary and its time does not differ from the neighboring ones..
Did you install the node from the release builds or from the source code?
Are there any other errors? Can you attach the full debug.log?

**Comment by Dylan-86** [comment]
Hi,
Installed from the build.

Debug attached.

[debug.log](https://github.com/pocketnetteam/pocketnet.core/files/8118901/debug.log)

**Comment by andyoknen** [comment]
@Dylan-86 It's really weird, but I can see that the synchronization is going on. Let's wait for full synchronization, or the moment when it stops altogether

**Comment by andyoknen** [comment]
@Dylan-86 Do you have any updates on this issue?

**Comment by Dylan-86** [comment]
> @Dylan-86 Do you have any updates on this issue?

It seems that it's solved, I didn't really do anything, it was something temporary
