### ISSUE TITLE
RPC cache breaks startup on 0.21

### ISSUE THREAD

**Issue by lostystyg** [pocketnetteam/pocketnet.core#215]
RPC cache is using [this](https://github.com/pocketnetteam/pocketnet.core/blob/4cc896a9894819df5eedf6b7a11027db7d42dda8/src/rpc/cache.cpp#L12) call to initialize current height. However, in 0.21 this call [requires chain to be already initialized](https://github.com/pocketnetteam/pocketnet.core/blob/a71df76fa8492aec8f6c9c18ef5371ef81548394/src/validation.cpp#L123). Because RPC initialization is much earlier than chain initialization, this assertion always fails.

As a workaround i suggest initializing rpc cache with height 0 and it will be updated on the first rpc call. At this point it will be safe because even if rpc call will come until chain is initialized, it will be [rejected](https://github.com/pocketnetteam/pocketnet.core/blob/a71df76fa8492aec8f6c9c18ef5371ef81548394/src/rpc/server.cpp#L333).

**Comment by lostystyg** [comment]
If this workaround is suitable, i will update bitcoin_upstream branch with it

**Comment by andyoknen** [comment]
> If this workaround is suitable, i will update bitcoin_upstream branch with it

Sounds reasonable

**Comment by lostystyg** [comment]
Suggested fix has been already applied in 0.21
