### ISSUE TITLE
Build fails in src/staker.cpp for `--disable-wallet`

### ISSUE THREAD

**Issue by d4rk5eed** [pocketnetteam/pocketnet.core#250]
**Describe the bug**
When application been built for `./configure --disable-wallet` it fails with `use of undeclared identifier 'CheckStake'` in src/staker.cpp

**To Reproduce**
1. ./autogen.sh
2. ./configure --disable-wallet
3. make

**Expected behavior**
Build success

**Desktop (please complete the following information):**
 - Version 0.20
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: x86_64-apple-darwin20.6.0
Thread model: posix

**Additional context**
Obviously that declaration is masqued with ENABLE_WALLET macros in pos.h, but function is still called in staker.cpp. To get the build running I've added ENABLE_WALLET macros into the body of Staker::worker. Don't know how correct it is.

**Comment by d4rk5eed** [comment]
It's finally failed with
```
Undefined symbols for architecture x86_64:
  "GetWalletForJSONRPCRequest(JSONRPCRequest const&)", referenced from:
      PocketWeb::PocketWebRpc::GenerateAddress(JSONRPCRequest const&) in libpocketcoin_server.a(libpocketcoin_server_a-PocketTransactionRpc.o)
  "EnsureWalletIsAvailable(CWallet*, bool)", referenced from:
      PocketWeb::PocketWebRpc::GenerateAddress(JSONRPCRequest const&) in libpocketcoin_server.a(libpocketcoin_server_a-PocketTransactionRpc.o)
ld: symbol(s) not found for architecture x86_64
```
I see the same problem with

**Comment by tawmaz** [comment]
We have never actually had a functioning build for Apple architecture.  It would be nice to get it working as we have had multiple requests from people wanting to run it on older macs.

**Comment by d4rk5eed** [comment]
@tawmaz thanks for reply. I can fix it, but seems that issue is not about mac rather than it's about methods' declarations

**Comment by tawmaz** [comment]
We don't normally build with --disable-wallet so it is likely there are some issues there.  Why do you want to build with wallet disabled?

**Comment by andyoknen** [comment]
@d4rk5eed  Is the issue still relevant?
