### ISSUE TITLE
Expanding the functionality of RPC caching

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.core#267]
## Stage 1
Implement the logic of choosing a method for clearing cached data:
- number of blocks to indicate the lifetime.
- manually clearing from the outside

## Stage 2
Implement access to the cache object from third-party classes, for example DB Repository or RPC interface

**Comment by lostystyg** [comment]
Also for now there is a bit mess up: unique cache object is created for each table, however it follows logic (in size, supported methods, etc) of one cache for every RPC table. Need to use one cache object for all or split cache size and supported methods between corresponding RPC tables
