### ISSUE TITLE
New node wallet address where?

### ISSUE THREAD

**Issue by testtubetony** [pocketnetteam/pocketnet.core#27]
A few noob questions... I followed the user guide and got my node running. It is synced up and looks to be functioning. I see it says to export my private key and save it somewhere safe, and to do this I need my wallet address. Where do I find my wallet address? 
I also see the guide says I get a node setup award as I need a small balance to start earning some koin, and that I can transfer some of my account balance to get things moving more quickly. How long before I receive said award, is it automatic or do I have to do anything, and what is the proper method to transfer some of my account balance into the node wallet? I think I see how to perform the transfer but I don't want to mess it up. Thanks in advance!

**Comment by andyoknen** [comment]
Welcome to the club)
I will try to answer your questions in order

To view a list of your addresses, you can, for example, use the RPC command:
> pocketcoin-cli listaddressgroupings
This command finds all possible addresses in your wallet, and also calculates the balances on these addresses

As for the reward, we had a reward program for starting a node at the very beginning, now it has been canceled.
But we have a new incentive program for setting up a so-called webnode - 
https://github.com/pocketnetteam/pocketnet.core/blob/master/doc/public_access.md
https://pocketnet.app/pocketnet_team?s=7dee078d50dbba971099071b654757fac5c178026027bdc27f8616ff91357a32

As for the balance, after finding out your node addresses (or creating a new one - getnewaddress), you can transfer your funds from other available sources. The more coins on your node, the higher the chance of winning.
