### ISSUE TITLE
Changing the accounting of reputation

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.core#298]
...

**Comment by the-real-vortex-v** [comment]
Removing/limiting the reputation system and not having an immediate replacement to moderate copypasta bots (the swave of accounts that scrape imgur and other sites) is really ruining the experience of the platform. There are now dozens/hundreds of accounts doing this on a daily basis. It looks really bad and inorganic.
By removing the moderation and not having features like the one mentioned in this ticket ready to go it's making the platform worse. I suggest putting back 1stars the way they where now and when you get this ready then releasing it.
