### ISSUE TITLE
Self-diagnosis

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.core#30]
Мысли влух.
Узел может иметь впамяти базу данных "mock" транзакций, удовлетворяющие необходимым для теста условиям - для публикации поста необходима регистрация, чтобы опубликовать больше постов нужна репутация.

В целом можно воспроизвести любую последовательность действий, имея техническую возможность к неограниченному кол-ву свободных выходов. Бд мок транзакций решает эту задачу, храня в памяти фиктивные выходы со средствами, которые можно использовать в валидации транзакций.

Управлемый цикл генерации цепи позволит в произвольном порядке генерировать блоки транзакций для достижения необходимой ситуации.

Sqlite in-memory db - нужна для снижения нагрузки hdd/ssd и для увеличения пропускной способности узла.

**Comment by vorot93** [comment]
А могли бы использовать MDBX, которая ACID и при этом делает mmap в ОЗУ
