### ISSUE TITLE
v0.20.25 Release

### ISSUE THREAD

**Issue by only1question** [pocketnetteam/pocketnet.core#332]

**Comment by only1question** [comment]
Added [v0.20.25-beta3](https://github.com/pocketnetteam/pocketnet.core/releases/tag/v0.20.25-beta3) for testing

**Comment by only1question** [comment]
Added one more Api get method in [v0.20.25-beta4](https://github.com/pocketnetteam/pocketnet.core/releases/tag/v0.20.25-beta4)

**Comment by gab-fer** [comment]
## The results of load testing for the test network.
### test.1.pocketnet.app
```
2 VCPU
4 GB RAM
SSD

threads=10
workqueue=100

duration 1 hour
```

| Test # | Threads / <br/> TX per sec | Count | Time AVG (ms) | Time MAX (ms) | Time MIN (ms) | RPC Pool <br/> exceeded |
| --- | --- | --: | --: | --: | --: | --: |
| 1 | 4 / 2 | 6096 | 236 | 1971 | 87 | 0 |
| 2 | 8 / 1 | 22401 | 266 | 9721 | 88 | 0 |
| 3 | 16 / 0.5 | 62472 | 399 | 24773 | 87 | 0 |
| 4 | 32 / 0.25 | 103845 | 638 | 56644 | 86 | 0 |

The method of generating a transaction in the test network - `pocketdb/web/PocketTransactionRpc.h::GenerateTransaction`
The following types of transactions were used in equal proportions:
```
Comment
Post
Rating
Subscription
```

**Comment by only1question** [comment]
Bench results:

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|        4,659,814.00 |              214.60 |    0.2% |      0.05 | `AssembleBlock`
|            2,362.96 |          423,197.80 |    0.2% |      0.01 | `Base58CheckEncode`
|            1,057.94 |          945,233.27 |    0.1% |      0.01 | `Base58Decode`
|            1,327.02 |          753,568.05 |    0.2% |      0.01 | `Base58Encode`
|              510.91 |        1,957,286.34 |    0.1% |      0.01 | `Bech32Decode`
|              648.32 |        1,542,457.66 |    0.4% |      0.01 | `Bech32Encode`
|          830,702.00 |            1,203.80 |    1.3% |      0.01 | `BenchLockedPool`

|            ns/block |             block/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|          628,602.00 |            1,590.83 |    1.6% |      0.01 | `CCheckQueueSpeedPrevectorJob`

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|            5,981.42 |          167,184.29 |    0.2% |      0.01 | `CCoinsCaching`

|             ns/elem |              elem/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|              199.27 |        5,018,304.26 |    1.1% |      0.02 | `ConstructGCSFilter`

0000ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff

|            ns/block |             block/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|          189,660.60 |            5,272.58 |    0.1% |      0.01 | `DeserializeAndCheckBlockTest`
|           71,740.20 |           13,939.19 |    0.0% |      0.01 | `DeserializeBlockTest`

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|                2.85 |      350,926,897.23 |    0.4% |      0.01 | `FastRandom_1bit`
|               11.31 |       88,436,992.65 |    0.1% |      0.01 | `FastRandom_32bit`

|             ns/elem |              elem/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|           21,514.37 |           46,480.57 |    1.1% |      0.01 | `MatchGCSFilter`

|            ns/block |             block/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|           18,678.06 |           53,538.75 |    0.2% |      0.01 | `MempoolEviction`

|             ns/leaf |              leaf/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|              173.06 |        5,778,372.67 |    0.2% |      0.02 | `MerkleRoot`

|             ns/byte |              byte/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|                2.92 |      341,996,328.33 |    0.1% |      0.03 | `RIPEMD160`

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|              447.07 |        2,236,769.07 |    0.7% |      0.01 | `RollingBloom`

|             ns/byte |              byte/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|                1.96 |      510,202,780.09 |    0.1% |      0.02 | `SHA1_test`
|                2.59 |      386,679,948.83 |    0.0% |      0.01 | `SHA256D64_1024`
|                9.38 |      106,623,289.74 |    0.2% |      0.01 | `SHA256_32b`
|                4.31 |      231,926,436.65 |    0.0% |      0.05 | `SHA256_test`
|                3.73 |      267,837,222.46 |    0.1% |      0.04 | `SHA512_test`

|               ns/op |                op/s |    err% |     total | benchmark
|--------------------:|--------------------:|--------:|----------:|:----------
|               36.93 |       27,077,226.55 |    0.2% |      0.01 | `SipHash_32b`
|          200,940.60 |            4,976.60 |    0.1% |      0.01 | `VerifyScriptBench`
