### ISSUE TITLE
`First` field in main.Transactions table sqlite db

### ISSUE THREAD

**Issue by andyoknen** [pocketnetteam/pocketnet.core#367]

**Comment by andyoknen** [comment]
Adding a "First" label to an object initialization transaction (account, content, or action) can help with complex selections.

For example, for accounts, the "first" entry will help you quickly get the registration date and the presence of a referral.

It is reasonable to add the index "Id"."First" together with the field.

**Comment by lostystyg** [comment]
Implemented via https://github.com/pocketnetteam/pocketnet.core/pull/360/commits/6e65ba67923eabe38965bdbdf1d8c5e6352603c8 and merged in #360 for 0.21 branch.
Implemented for `feature/db_optimizations` branch [here](https://github.com/pocketnetteam/pocketnet.core/pull/502/commits/80ac6ff30fcc6302d8872d4728f6c7f946a0525d#diff-2f5df38ccf75ad3f887caa21950683873dd76dc84defbc419abb8a908986abacR53-R70)
