### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by turowicz** [pocketnetteam/pocketnet.core#38]
It would be much easier if we could just have a `docker run` command without having to go through details of how a node operates and dealing with version updates.

Any plans for docker?

**Comment by turowicz** [comment]
I have been using this previously but it needs updating to latest version - which is a hussle I'm sure you understand.

https://github.com/turowicz/pocketnet/blob/master/Dockerfile

**Comment by turowicz** [comment]
cc @pocketnetteam

**Comment by andyoknen** [comment]
@turowicz At the moment, the node takes a lot of RAM, which is not always convenient when using docker. We have experience building and running a node in docker and we will distribute via docker.io a little later.
