### ISSUE TITLE
crypto currency helper scripts for Debian based Linux distributions and subsystems

### ISSUE THREAD

**Issue by nnmfnwl7** [pocketnetteam/pocketnet.core#39]
Hi. Im freelance developer, 

Right now I am mostly focusing on helper scripts that are able to build not-only pocketcoin wallets/daemon from official source code github repositories on Debian Linux based operating systems or subsystems.

Secure run/build sandbox with firejail, Also ARM build support, easy to manual rebuild in secured sandbox...

These helper scripts are already in testing stage and will be published soon. Right now only readme file has been published on https://github.com/nnmfnwl7/cc.setup.helper.debian

For more details/usecases please read follow link. Feel free to share your ideas and feedback. Thank you.

**Comment by andyoknen** [comment]
Could you describe in more detail the application scenarios of your work?

**Comment by nnmfnwl7** [comment]
> Could you describe in more detail the application scenarios of your work?

As I am working on secured build and automatization blockchain wallets, and im also running pocketnet node, i can see very problematic for people to setup pocketcoin node(staking), also by https://github.com/pocketnetteam/pocketnet.core/releases/tag/v0.19.14 no other architectures and operating systems has been released, also testing new versions is problematic,
prepare and build wallets from source code.

With this scripts, users will just push few commands to keyboard and they will have fully functional and configured pocketnet staking node, also they will be able to update their node by one command(GUI-QT also daemon versions)

These scripts are here to do whole build process in resource friendly Sandbox environment called firejail. Also generated run scripts allows to run whole staking node in firejail sandbox.

These scripts are not only for those who want to stake, also for those who want to test other versions like sqlite version is. 

These scripts could be useful for developers for custom builds.

These scripts are not intended only for pocketcoin node, they can also build bitcoin,litecoin,pivx,dash, verge and bocknet full wallet nodes. As these wallets support atomic-swap technology, there is also script to pre-configure them with True Decentralized Exchange named BlockDX which is part of Blocknet project. Hopefully i will see pocketnet-team interest to join BlockDX DEX, to secure PKOIN trading on DEX as part of decentralization which is directly related to support freedom of speech.
