### ISSUE TITLE
SQlite DB size growth 

### ISSUE THREAD

**Issue by davkastheranger19** [pocketnetteam/pocketnet.core#400]
I'm running two nodes and each has a pocketdb folder size of over 90GB.
Is there any automation we can add to clean up the DBs to keep their size in check?
I see the minimum recommendation is 100GB, but that suggestion may need to be increased if the size is expected to continue to grow. The total size of the pocketcoin folder is 129GB on each of the two nodes.

Thanks

**Comment by andyoknen** [comment]
> I'm running two nodes and each has a pocketdb folder size of over 90GB. Is there any automation we can add to clean up the DBs to keep their size in check? I see the minimum recommendation is 100GB, but that suggestion may need to be increased if the size is expected to continue to grow. The total size of the pocketcoin folder is 129GB on each of the two nodes.
> 
> Thanks


Hi! Regarding the documentation, I have made the necessary edits at the moment in README.MD https://github.com/pocketnetteam/pocketnet.core/pull/402

Regarding database compression, there are several options here:
1. manual compression when **the node is stopped** 
  You can run the `vacuum;` command via the sql interface to compress the database - This may take several hours and additional disk space for temporary data.
2. automatic during operation
  It would also be possible to do this automatically while the node is running, but this operation is likely to slow down the node. I will create an #403 about this.
