### ISSUE TITLE
Old node with IP 46.175.122.243 (0.20.19 according to block explorer)

### ISSUE THREAD

**Issue by HiHat** [pocketnetteam/pocketnet.core#410]
another user gave the go-ahead to add his ip to the list. 46.175.122.243
Unfortunately, not all users are friends with github, so I will ask people who will give consent, I will write here.

_Originally posted by @gf110 in https://github.com/pocketnetteam/pocketnet.core/issues/194#issuecomment-1046883359_

**Comment by andyoknen** [comment]
https://github.com/pocketnetteam/pocketnet.core/pull/505
