### ISSUE TITLE
Reddit Community Bastyon Placeholder

### ISSUE THREAD

**Issue by Francewhoa** [pocketnetteam/pocketnet.core#430]
Hello Bastyon community :)

I'm new to Bastyon. It's my favourite alternative to Facebook, Twitter, and all social medias.

This is to notify you that, as a volunteer, I created this placeholder Reddit community at https://www.reddit.com/r/Bastyon/ By "placeholder" I mean that I reserved the community name `Bastyon` on Reddit.

Volunteers interested in both Reddit and in maintaining this Reddit community are welcome to contact me Francewhoa at https://bastyon.com/francewhoa Asking to add you as moderator.

For now, I added links from this Reddit community to https://bastyon.com In turn, this might bring more people to the Bastyon community. As of 2020, Reddit claim to have 52 million active real users.

If someone is wondering about my intention. I do **NOT** recommend Reddit. I very seldom use it. Because of it's very long history of censorship. 

In the future, if the Bastyon community need a discussion software, in addition to Bastyon itself, I suggest https://www.discourse.org The main risk with Discourse is that it's controlled by the centralized for-profit organization "Civilized Discourse Construction Kit, Inc." Which in turn, is financed by the centralized for-profit, venture capital funding from [First Round](https://en.wikipedia.org/wiki/First_Round_Capital), [Greylock](https://en.wikipedia.org/wiki/Greylock_Capital_Management), and [SV Angel](https://en.wikipedia.org/wiki/SV_Angel). All of the above means that "Civilized Discourse Construction Kit, Inc."  and venture capital are at very high risk of prioritizing money over people.

You're welcome to ask me if you have any questions, concerns or suggestions about any of the above

Cheers,

Francewhoa

**Comment by andyoknen** [comment]
Hi @Francewhoa,

Thank you for your contribution!) I checked your issue and left some comments. I hope for a long cooperation!)
