### ISSUE TITLE
How to edit a published Article?

### ISSUE THREAD

**Issue by Francewhoa** [pocketnetteam/pocketnet.core#435]
## Challenge

About https://bastyon.com I wrote an Article. Published it. Was able to edit it. Then a few days later, when I tried to edit this published Article, its **Edit Post** button is not display. How do I edit this published Article?

Below is the same question as above. But with details if you're interested in those.

## Steps To Reproduce

1. Go to https://bastyon.com/index

1. Using the **What's new?** group, click on this **To write an article** link
![to_write_an_article---screenshot---francewhoa---ksnip---2022-10-09---192403](https://user-images.githubusercontent.com/119942/194784376-ca179ccc-55d0-4767-8555-92e23b348816.png)

1. The **New Longread** window will open. Fill the form. Publish it.

1. Click on this **Edit Post** to do any change to your Article. This is successful. As you're able to edit your article.
![Edit_Post---screenshot---francewhoa---ksnip---2022-10-09---174618](https://user-images.githubusercontent.com/119942/194785057-e982d77d-829c-4c3b-84e1-00aca923a2f7.png)

1. Wait a few days

1. Try to edit your article. Somehow, this **Edit Post** button is gone. This is the challenge.
![bouton_gone---screenshot---francewhoa---ksnip---2022-10-09---175029](https://user-images.githubusercontent.com/119942/194785098-d3dfc315-0767-4fe3-b959-11d6b22008e2.png)

1. How do I edit this published Article again? The needed end result is that users need to be able to edit their Article at any time. Using the same **Edit Post** button. The number 2 in the screenshot above shows the expected location of this button.

This is an example of an article I wrote today, October 9th, 2022. Presently, I can still edit it. But somehow, within the next 5 days, I will not be able to edit it at https://bastyon.com/francewhoa?s=66e32a753d531a573efa212171fce77ff5570927e1ac8684402f4a9e92abe47a&mpost=true

Link to another of my article I wrote on October 4th, 2022. But somehow, today Oct 9th, 2022 I am not able to edit it. I need to edit at https://bastyon.com/francewhoa?s=fb84354526d3a0f94b8703ac5ba9de4b85c835fdd355d8b6b90081f92e961e54&mpost=true

Link to my other test article I created. Which I'm presently able to edit at https://bastyon.com/francewhoa?s=841b9e3105d19763db212a23d3132cf9dfaf09e3050014b3549c30c6bdfb6a42&mpost=true

## User Story

If somehow this challenge above is by design, I suggest the new feature/new User Story at https://github.com/pocketnetteam/pocketnet.core/issues/436

**Comment by Francewhoa** [comment]
I was able to reproduce this challenge twice. With 2 new Articles. Roughly two days after I published these, their **Edit Post** button is no longer display.

In comparison, for all my comments, their **Edit Comment** button are always visible. Regardless of theses comments publication date.

**Comment by andyoknen** [comment]
Hello @Francewhoa,
First of all, I want to express my gratitude for your activity and feedback. Unfortunately, the developers are now overloaded and cannot respond more quickly.

Regarding your question, there is a restriction for editing content, which is due to prevent situations when positive content is created, gaining popularity, and after a while the content of the content changes. This can be used in various "harmful" scenarios.

https://github.com/pocketnetteam/pocketnet.core/blob/07d4b92c487d8e7e997b2d2787a1474041421dcd/src/pocketdb/consensus/social/Article.hpp#L141-L143
