### ISSUE TITLE
When typing an update on Bastyon, edit box doesn't scroll into view

### ISSUE THREAD

**Issue by gked** [pocketnetteam/pocketnet.core#486]
**Describe the bug**
When I type an update in Bastyon app on Android, edit box doesn't scroll into view and I end up not seeing the cursor or what I am typing. 

**To Reproduce**
1. Open Bastyon app on android
2. Click on white cross in the blue icon to create a new post
3. Tap on the edit box that has "What's new?" placeholder
Expected: The edit box scrolls into view an I can see the cursor and what I am typing
Actual: The edit box doesn't scroll into view. I can however still type characters, it's just I don't see what I am typing.

**Screenshots**
Before tapping in the edit box

![9a69f222-5ee7-4e5f-8aa1-84eb6dfbcf12](https://user-images.githubusercontent.com/12704474/204997202-f9c07999-a129-42c0-b184-f297665ebd8e.jpeg)

After tapping on the edit box

![89555083-6ead-4ee4-8f85-b3b891a1f752](https://user-images.githubusercontent.com/12704474/204996786-daa41775-c3b4-46c7-9efe-e274ae603f68.jpeg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S20 FE 5G
 - OS: Android 12 with One UI version 4.1
 - Browser: Bastyon App
 - Version 1.7.17

**Comment by andyoknen** [comment]
Thank you for your response! Could you please move this issue to the repository https://github.com/pocketnetteam/pocketnet.gui

**Comment by gked** [comment]
Closing since the issue got moved into https://github.com/pocketnetteam/pocketnet.gui/issues/783
