### ISSUE TITLE
Request to add an IP address to the source code

### ISSUE THREAD

**Issue by Damien36** [pocketnetteam/pocketnet.core#487]
This issue is  a request to add an IP address to the source code of the node. This is necessary to maintain and expand the network so that new nodes can connect to the network using the maximum number of peers. 

The current list of nodes can be seen in the file https://github.com/pocketnetteam/pocketnet.core/blob/0.20/contrib/seeds/nodes_main.txt

Please fill in the fields below to review the request:

IPv4 Address: 50.65.56.253
IPv6 Address (If available): N/A
Public HTTP API Port: 38081 (default)
Public WS API Port: 8087 (default)

**I confirm that my node is available at the specified addresses and ports 24/7**

**Comment by andyoknen** [comment]
```sh
~ » curl --location --request POST '50.65.56.253:38081/' \                                                                      brangr@iMak
--header 'Content-Type: application/json' \
--data-raw '{"method":"getnodeinfo","params":[]}'
curl: (28) Failed to connect to 50.65.56.253 port 38081 after 75012 ms: Operation timed out
Time: 0h:01m:15s
~ »                                                                                                                             brangr@iMak
~ » ping 50.65.56.253                                                                                                           brangr@iMak
PING 50.65.56.253 (50.65.56.253): 56 data bytes
64 bytes from 50.65.56.253: icmp_seq=0 ttl=49 time=231.176 ms
64 bytes from 50.65.56.253: icmp_seq=1 ttl=49 time=276.257 ms
64 bytes from 50.65.56.253: icmp_seq=2 ttl=49 time=227.112 ms
^C
--- 50.65.56.253 ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 227.112/244.848/276.257/22.271 ms
Time: 0h:00m:03s
```

**Comment by andyoknen** [comment]
@Damien36

**Comment by Damien36** [comment]
I've opened the right ports and it should work now. Thanks.

**Comment by andyoknen** [comment]
I will add your IP to the list, but if you want to support "clients" you need to open and forward ports 38081 and 8087

You can check port availability using this website (made by one of the users):
https://pocketnetexplorer.azurewebsites.net/#/nodeinfo/50.65.56.253
