### ISSUE TITLE
Podcast functionality on Bastyon

### ISSUE THREAD

**Issue by gked** [pocketnetteam/pocketnet.core#489]
**Is your feature request related to a problem? Please describe.**
Creating an issue for a podcast request posted on Bastyon. Unfortunately, I lost the link to the post requesting it.

**Describe the solution you'd like**
Simple podcast management (upload, listen/watch) user experience. 

**Describe alternatives you've considered**
I don't think there is an alternative unless users are going to upload podcasts, using a video uploader. I am not even sure it is possible.

**Comment by andyoknen** [comment]
#488

A new transaction (audio) think perfect for the implementation of podcasts. The inclusion of this transaction is not yet approved, but definitely after release 0.21 versions, which is planned in December

**Comment by gked** [comment]
That's great, @andyoknen - thank you.
Just for my own education. Is this the part that will build protocol support for audio streaming but not the UI, correct? At least that's what the PR seems to show if my limited knowledge in C++ doesn't fail me here. Is there a ticket tracking UI part of things? If not should I create one?

Also, what does the approval process look like? Is there a review that happens around additional functionalitie in the protocol?

**Comment by andyoknen** [comment]
@gked The essence is that blockchain (server) and GUI (wallet and social network) are in different repositories. The interface is located in the next repository ‘pocketnet.gui'. The audio content storage will be performed (currently) network of servers based on the Peertube project (it supports audio content, along with video). This pool adds support for a new transaction type, limits on its creation, as well as consensus rules and API on working with this type of content. Support audio in Peertube seems to be over, interface work will start soon.
