### ISSUE TITLE
Dead link in Readme 

### ISSUE THREAD

**Issue by gked** [pocketnetteam/pocketnet.core#498]
**Describe the bug**
Following a link in the Readme file navigates to a page with a 404 error.

**To Reproduce**
1. Go to https://github.com/pocketnetteam/pocketnet.core/tree/0.20
2. Click on "Read more in the article."
4. See 404 error on navigation. 

**Expected behavior**
A link should resolve.

**Screenshots**
![Screenshot_20221210-174445_Brave](https://user-images.githubusercontent.com/12704474/206882607-97a78857-0aba-49fd-9707-66c92e416832.jpg)

**Desktop (please complete the following information):**
 

**Smartphone (please complete the following information):**

**Additional context**
A

**Comment by andyoknen** [comment]
@gked Thank you!
