### ISSUE TITLE
Paid Content Subscriptions

### ISSUE THREAD

**Issue by only1question** [pocketnetteam/pocketnet.core#506]
Enable paid content subscriptions.
The content author sets the subscription price. And can create content that is available to paid users. For users, there must be a subscription transaction for paid author content.

**Comment by nnmfnwl** [comment]
This would be amazing and very useful feature to have, many content creators could come here and stay protected under the wings of decentralized network. Question is how this feature would be implemented as user experience. There are already 3 options to create a post: (1 visible for everyone), (2 visible only for subscribers), (3 visible only for bastyon users) and would be great to have 2 more options (4 visible only for payed subscribers(monthly payment)) and (5 visible only pay to view(set price by post)), or maybe implement "pay to view" option as combination to be available for both users who are "payed subscribers" or ones who "pay to unlock" where author can set custom price per post/video/audio/image.
