### ISSUE TITLE
Can't complete full sync

### ISSUE THREAD

**Issue by Linkdealer** [pocketnetteam/pocketnet.core#51]
Greetings! I can't complete a full sync. Made four attempts, spent a week on it.

So what I am doing:

1) download https://3.pocketnet.app/checkpoint/pocketnet.checkpoint.latest.tgz;
2) update the data following the instructions;
3) launch the program and see that I have 99.92% synchronization and 382 blocks remain to be downloaded;
4) I let the program work, sometimes I see connections to peers appear in the debug window. There is a download and everything seems to be happening as it should.

The problem is that the % of synchronization only decreases over time, and the number of blocks to download only becomes larger.

For 1-2 days, the situation only gets worse.

I tried to run the program with the parameters -listen = 0 -blocksonly = 1 but it didn't get the desired full synchronization.

I am using version pocketnetcore_0.19.13_win_x64_setup.exe on Windows 7 operating system with RAM 8Gb

How to achieve complete synchronization so that the program can work properly? Thanks.

**Comment by andyoknen** [comment]
Unfortunately, 8GB of RAM is not enough to run a full-fledged node. We are working on a major update that will be released this fall - in it, the memory requirements will be greatly reduced due to the transition to a NON-in-memory database.

**Comment by andyoknen** [comment]
Also, if there are synchronization problems, you must first refer to the log file - debug.log in the database directory

**Comment by Linkdealer** [comment]
> Unfortunately, 8GB of RAM is not enough to run a full-fledged node. We are working on a major update that will be released this fall - in it, the memory requirements will be greatly reduced due to the transition to a NON-in-memory database.
[debug.log](https://github.com/pocketnetteam/pocketnet.core/files/7231417/debug.log)

**Comment by Linkdealer** [comment]
> Unfortunately, 8GB of RAM is not enough to run a full-fledged node. We are working on a major update that will be released this fall - in it, the memory requirements will be greatly reduced due to the transition to a NON-in-memory database.

Thank you andyoknen! Will we see a new version with reduced requirements this year? And what will be the new requirements for RAM? Is there a set release date?

I am looking in the debug.log file but my knowledge of the program is not enough to determine the problem. I am attaching this file, if possible, tell me which lines should have suggested to me about the lack of RAM.
Thanks!
[debug.log](https://github.com/pocketnetteam/pocketnet.core/files/7231426/debug.log)

**Comment by Linkdealer** [comment]
Perhaps the problem with synchronization is also in the minimum number of peers and in the fact that they may not send or receive data for a long time. Is RAM to blame for this? I do not know
![2021-09-30_22-35-00](https://user-images.githubusercontent.com/91337175/135520548-f65d1a9c-2aeb-4da3-a8ea-a1e6e760f3bf.png)
.

**Comment by andyoknen** [comment]
At the moment, the consumption of the RAM node is approximately 12-14GB

Now in the process of testing and final improvements of the feature/sqlite branch - RAM requirements of about 1-2 GB and SSD disk with free space of at least 50 GB in the future for the next year.

I think within a month we will start beta testing sqlite (0.20.0) version in the main network and maybe you want to participate?

**Comment by Linkdealer** [comment]
> At the moment, the consumption of the RAM node is approximately 12-14GB
> 
> Now in the process of testing and final improvements of the feature/sqlite branch - RAM requirements of about 1-2 GB and SSD disk with free space of at least 50 GB in the future for the next year.
> 
> I think within a month we will start beta testing sqlite (0.20.0) version in the main network and maybe you want to participate?

Thanks for the information! I'll gladly help you with testing, but right now I don't have an SSD, only an HDD. I have already ordered a new SSD for this purpose, but I'm not sure how quickly it will be shipped.

**Comment by andyoknen** [comment]
HDD will also work, but several times slower - this is due to the fact that sqlite works directly with the database file on disk, without unloading data into RAM

**Comment by Linkdealer** [comment]
> HDD will also work, but several times slower - this is due to the fact that sqlite works directly with the database file on disk, without unloading data into RAM

OK! But with an SSD it will be better, as I understand it. In any case, I am ready to help you if you need it. With SSD or not (temporarily). Give me the appropriate instructions when needed.
