### ISSUE TITLE
Hello, thanks for your enquiry. I will process your request in #533

### ISSUE THREAD

**Issue by loner11111** [pocketnetteam/pocketnet.core#540]
Hello, thanks for your enquiry. I will process your request in #533

_Originally posted by @andyoknen in https://github.com/pocketnetteam/pocketnet.core/issues/535#issuecomment-1412476515
Hello, have you added my ip address to the Bastion code, or do you have any problems?

**Comment by andyoknen** [comment]
Your IP has been added to the list of public sites
https://github.com/pocketnetteam/pocketnet.core/pull/536
