### ISSUE TITLE
21.2 beta never finishes install

### ISSUE THREAD

**Issue by graebeerd** [pocketnetteam/pocketnet.core#566]
It looked like I was off chain after successfully installing 21.2 and running for two days so downloaded a snapshot and extracted and overwrote existing files. Rebooted after extraction, started 21.2 and it crashed (on two attempts) returning the error you see in the attached jpeg and debug.log file.

Edition	Windows 11 Pro
Version	22H2
Installed on	‎5/‎16/‎2022
OS build	22624.1391
Experience	Windows Feature Experience Pack 1000.22639.1000.0
24 GB RAM

![21 2beta](https://user-images.githubusercontent.com/50458374/223704792-3687b84f-8d2b-4ee4-b737-c711b22a50b2.jpg)
[debug_21.2.txt](https://github.com/pocketnetteam/pocketnet.core/files/10920223/debug_21.2.txt)

**Comment by andyoknen** [comment]
I'm confused that you overwritten existing files with new files from the snapshot instead of deleting existing data and unpacking the snapshot. The fact is that leveldb databases consist of many files and simply overwriting the entire directory can severely disrupt the structure of the database.

**Comment by graebeerd** [comment]
You're right, just installed the latest release without any problems and will, if needed, not overwrite next time. Thank You
