### ISSUE TITLE
21.3 not marked as latest in docker hub for recent update

### ISSUE THREAD

**Issue by nienburg** [pocketnetteam/pocketnet.core#590]
**Describe the bug**
When doing docker pull, its not pulling down new images even though 21.3 has been released.
**To Reproduce**
# docker pull pocketnetteam/pocketnet.core:latest
latest: Pulling from pocketnetteam/pocketnet.core
Digest: sha256:94ff35518d9a8ac764c615e5170229318fbee6d6e5bb4cf0237865a823ddb296
Status: Image is up to date for pocketnetteam/pocketnet.core:latest
docker.io/pocketnetteam/pocketnet.core:latest

**Expected behavior**
shoulud download new images to upgrade from 21.2 to 21.3
**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by lostystyg** [comment]
The latest has been updated, is it working for you now @nienburg?

**Comment by nienburg** [comment]
yes was corrected not too long after I opened this bug.  Please close at your convenience and appreciate the team's support!
