### ISSUE TITLE
pocketnet.app and bastyon.com are down

### ISSUE THREAD

**Issue by bulrush15** [pocketnetteam/pocketnet.core#599]
**Describe the bug**

Are they having problems or are they down for good?

Please check Pocketnet documentation if these websites no longer exist.

**Comment by andyoknen** [comment]
> **Describe the bug**
> 
> Are they having problems or are they down for good?
> 
> Please check Pocketnet documentation if these websites no longer exist.

Is the problem still relevant? I don't observe any problems..

**Comment by bulrush15** [comment]
Sorry. I forgot my employer blocks some websites. That's probably what it is. This can be closed.

**Comment by andyoknen** [comment]
you can try the application with the `Electron Proxy` proxy enabled in the settings - in this mode, the application does not need domains and all work is done exclusively on IP directly with nodes on the network
