### ISSUE TITLE
btcpop wallet and staking issues

### ISSUE THREAD

**Issue by cregist** [pocketnetteam/pocketnet.core#61]
As you may know, the btcpop exchange PKOIN wallet has been under maintenance for over two weeks. According to btcpop sopport, PKOIN has suffered multiple chain splits, and currently has no available block explorer API. 

Does the pocketnet team have any insights into this issue?

Thanks.

**Comment by cregist** [comment]
> is only a technical problem of protocol negotiation with BTCPOP

Thanks for your answer. I'm just a little bit frustrated with the situation.

**Comment by andyoknen** [comment]
We are negotiating with BTCPOP and we have been informed that the work has been restored. I will close this issue and return it if necessary.
