### ISSUE TITLE
Official Docker Run Command Does Not Work

### ISSUE THREAD

**Issue by cahlenlee** [pocketnetteam/pocketnet.core#622]
Running the official Docker command listed in the main ReadMe doesn't work:

"sudo docker run -d --name=pocketnet.main --ulimit nofile=65536:65536 --log-driver local --log-opt max-size=10m --log-opt max-file=3 -p 37070:37070 -p 38081:38081 -p 8087:8087 -v /var/pocketnet/.data:/home/pocketcore/.pocketcoin pocketnetteam/pocketnet.core:latest"

Results in this output, but no running container:

"5bd24e652d1da8dedd0f73741320fbb2bbe1b90545babc5f7edba917793ed9b3"

**Comment by lostystyg** [comment]
Please exec `docker logs 5bd24e652d1da8dedd0f73741320fbb2bbe1b90545babc5f7edba917793ed9b3` or whatever was the last output from `docke run ...` command and provide an output here. Might there be the same error as in #623?

**Comment by cahlenlee** [comment]
Yes, same error.

**Comment by lostystyg** [comment]
So the same workaround applies. You can pass `--user root:root` argument to your command or manually create datadir and ensure it is owned by `1000:1000`
