### ISSUE TITLE
No Documentation on Submitting Posts via CLI

### ISSUE THREAD

**Issue by cahlenlee** [pocketnetteam/pocketnet.core#710]
I'm trying to figure out how to submit a post from a Linux Terminal. There appears to be no documentation on how to do this, and nobody in the community seems to know.

Can you provide documentation on this? Even just a simple example of how to use pocketcoin-tx for a basic post could get me started.

**Comment by andyoknen** [comment]
I understand your question. Generating "social" content through the cli is fraught with many difficulties - signing transactions, choosing UTXO, and so on.

Instead, we started developing our SDK for these purposes. This is a JS library that will help you use the network - node selection, transaction creation, etc. The project is under early development and does not have documentation yet, but you can subscribe to the repository and follow its development.

https://github.com/pocketnetteam/pocketnet.proxy
