### ISSUE TITLE
Failed to build latest version of pocketnet core node, because of incomplete CNode class.

### ISSUE THREAD

**Issue by nnmfnwl** [pocketnetteam/pocketnet.core#724]
In file included from pocketcoind.cpp:13:
In file included from ./init.h:14:
In file included from ./statistic.hpp:18:
./net.h:227:75: error: member access into incomplete type 'CNode'
    virtual bool SendMessages(CNode* pnode) EXCLUSIVE_LOCKS_REQUIRED(pnode->cs_sendProcessing) = 0;
                                                                          ^
./net.h:47:7: note: forward declaration of 'CNode'
class CNode;
      ^

**Comment by nnmfnwl** [comment]
Pocketcoin core node build/compilation process is affected when used clang/++ not gcc/++.

**Comment by andyoknen** [comment]
> Pocketcoin core node build/compilation process is affected when used clang/++ not gcc/++.

Could you create a docker image to reproduce the problem?
