### ISSUE TITLE
Support for WebP and Avif image formats

### ISSUE THREAD

**Issue by Getron** [pocketnetteam/pocketnet.core#738]
**Is your feature request related to a problem? Please describe.**
I have all of my sites with webp and avif formats of images, therefore, Bastyon is not supporting this formats yet, and it is crucial to support modern formats, because, more and more web pages uses this formats, and if you don't support, for example, on upload, or inserting links with webp or avif images, it won't be showed, and this looks bad.

**Describe the solution you'd like**
Bastyon, as a modern and abitious portal should support this formats, in any way.

**Describe alternatives you've considered**
There is no alternative, we should be able to share links with webp and avif image formats too, like you do with jpg and png.

**Additional context**

**Comment by andyoknen** [comment]
https://github.com/pocketnetteam/pocketnet.gui/commit/131993ab474fc578b2b1d3aee0b20d62b07094e4

I was told that somewhere in this PR there is an addition of support for the specified image formats for uploading.

**Comment by andyoknen** [comment]
Support for these formats should have been enabled, although I couldn't find a suitable PR.
