### ISSUE TITLE
 alpha-0.20.1 Pre-release installing question

### ISSUE THREAD

**Issue by Magic90007** [pocketnetteam/pocketnet.core#81]
Via to instructions I have to copy the DB "https://3.pocketnet.app/checkpoint/pocketnet.checkpoint.sqlite.tgz"  into the folder "Linux: \.pocketcoin\checkpoints\main.sqlite3". Right? Sorry, but I cannot find ".pocketcoin" or "checkpoints" folder in my system. Could you help me plz to find the "\.pocketcoin\checkpoints\main.sqlite3"?

**Comment by tintin-1929** [comment]
Hi, the .pocketcoin directory is hidden so if you can try this command "cd ~/.pocketcoin" that should change the current directory to the .pocketcoin directory. This works on my debian system when I do it under the user who installed pocketnet.core. Hope this is helpful.

**Comment by the-real-vortex-v** [comment]
> Via to instructions I have to copy the DB "https://3.pocketnet.app/checkpoint/pocketnet.checkpoint.sqlite.tgz" into the folder "Linux: .pocketcoin\checkpoints\main.sqlite3". Right? Sorry, but I cannot find ".pocketcoin" or "checkpoints" folder in my system. Could you help me plz to find the ".pocketcoin\checkpoints\main.sqlite3"?

Extract the .tar.gz or .tgz to ".pocketcoin\checkpoints". I got confused as well. They for some reason are talking about extracting to a directory but they are talking about the file name.

cp pocketnet.checkpoint.sqlite.tgz ~\.pocketcoin\checkpoints
cd ~\.pocketcoin\checkpoints
tar -xvf pocketnet.checkpoint.sqlite.tgz

^ - that's what you should do.
