### ISSUE TITLE
Fatal Internal Error

### ISSUE THREAD

**Issue by Oldman-Sam** [pocketnetteam/pocketnet.core#83]
Keep getting some kind of internal error in my node once in a while: 

> 2021-11-06T14:19:09Z RIDB rollback to block height 1427851 success!
> 2021-11-06T14:19:09Z RIDB rollback to block height 1427850 success!
> 2021-11-06T14:19:09Z 700004: Transaction RI data Not Found (5e9305e3119f376eb5631e0eb52b3c270055575e4906f0edc9a2a4832fb07f5b)
> 2021-11-06T14:19:09Z ERROR: Failed find reindexer transaction part (5e9305e3119f376eb5631e0eb52b3c270055575e4906f0edc9a2a4832fb07f5b)
> 2021-11-06T14:19:09Z ERROR: ConnectTip: ConnectBlock 6f82d509e04ab96d4f585bf5c82b9de126aecec3aa6653ede850973f2aead46f failed, failed-find-rtransaction (code 96)
> 2021-11-06T14:19:09Z 700004: Transaction RI data Not Found (5e9305e3119f376eb5631e0eb52b3c270055575e4906f0edc9a2a4832fb07f5b)
> 2021-11-06T14:19:09Z ERROR: Failed find reindexer transaction part (5e9305e3119f376eb5631e0eb52b3c270055575e4906f0edc9a2a4832fb07f5b)
> 2021-11-06T14:19:09Z ERROR: ConnectTip: ConnectBlock c5b720b6efe8bbefe877496095d51f010d80d22faac539178a34b0096f7bbb10 failed, failed-find-rtransaction (code 96)
> 2021-11-06T14:19:20Z Available coins count 3351 BestHeader: 1427852 0bc2036b31afc6648e6c999ad360733cabbb27b41e199f3596941ddd64a29428
> 2021-11-06T14:19:29Z RIDB rollback to block height 1427851 success!
> 2021-11-06T14:19:29Z RIDB rollback to block height 1427850 success!
> 2021-11-06T14:19:31Z 700004: Transaction RI data Not Found (2bba2e99af9cb0a18e7b3011ff06df477bdb299718e20a185ef602e2a5c710b3)
> 2021-11-06T14:19:31Z ERROR: Failed find reindexer transaction part (2bba2e99af9cb0a18e7b3011ff06df477bdb299718e20a185ef602e2a5c710b3)
> 2021-11-06T14:19:31Z ERROR: ConnectTip: ConnectBlock 7829874dda0a177e544f2537b155c6dc2663b02c40bb0bea1e349ac919ce1f40 failed, failed-find-rtransaction (code 96)
> 2021-11-06T14:19:31Z ERROR: UndoReadFromDisk: Deserialize or I/O error 2 (25) - CAutoFile::read: end of file: iostream error
> 2021-11-06T14:19:31Z ERROR: DisconnectBlock(): failure reading undo data
> 2021-11-06T14:19:31Z ERROR: DisconnectTip(): DisconnectBlock c5b720b6efe8bbefe877496095d51f010d80d22faac539178a34b0096f7bbb10 failed
> 2021-11-06T14:19:31Z *** Failed to disconnect block; see debug.log for details
> 2021-11-06T14:19:31Z Error: Error: A fatal internal error occurred, see debug.log for details
> 2021-11-06T14:22:54Z GUI: Check updates result: no new versions (https://github.com/pocketnetteam/pocketnet.core/releases/latest)
> 2021-11-06T14:25:05Z ERROR: ProcessNewBlock: ActivateBestChain failed (Failed to disconnect block; see debug.log for details (code 0))
> 2021-11-06T14:25:05Z Warning! Block generate (CheckInputs): d671e56fc680334cb1c4b064f7b985e026e83187ca504072a1de37937e5a4a01
> 2021-11-06T14:25:05Z Warning! Block generate (CheckInputs): 81bb31de8caab4977851d1167285126fcc28a7e97953880945d6c604e78dbded
> 2021-11-06T14:25:05Z Available coins count 3351 BestHeader: 1427851 c5b720b6efe8bbefe877496095d51f010d80d22faac539178a34b0096f7bbb10
> 2021-11-06T14:25:05Z ERROR: UndoReadFromDisk: Deserialize or I/O error 2 (25) - CAutoFile::read: end of file: iostream error
> 2021-11-06T14:25:05Z ERROR: DisconnectBlock(): failure reading undo data
> 2021-11-06T14:25:05Z ERROR: DisconnectTip(): DisconnectBlock c5b720b6efe8bbefe877496095d51f010d80d22faac539178a34b0096f7bbb10 failed
> 2021-11-06T14:25:05Z *** Failed to disconnect block; see debug.log for details
> 2021-11-06T14:25:05Z Error: Error: A fatal internal error occurred, see debug.log for details
> 2021-11-06T14:25:05Z Shutdown: In progress...
> 2021-11-06T14:25:05Z opencon thread exit
> 2021-11-06T14:25:05Z addcon thread exit
> 2021-11-06T14:25:05Z net thread exit
> 2021-11-06T14:25:15Z ERROR: ProcessNewBlock: ActivateBestChain failed (Failed to disconnect block; see debug.log for details (code 0))
> 2021-11-06T14:25:15Z msghand thread exit
> 2021-11-06T14:25:15Z scheduler thread interrupt
> 2021-11-06T14:25:15Z Pocketcoin Staker terminated
> 2021-11-06T14:25:15Z [default wallet] keypool return 1
> 2021-11-06T14:25:15Z Dumped mempool: 0s to copy, 0.042037s to dump

Running the newest node on Windows 10. My solution has been to redownload the the checkpoint file and replace everything. I was hoping the past few updates would fix this but it's been about 2 or so versions and I get this issue maybe once a week?

**Comment by tawmaz** [comment]
This is the known BlockUndo issue which we are still working on finding root cause for. It is characterized by the error message below:

ERROR: UndoReadFromDisk: Deserialize or I/O error 2 (25) - CAutoFile::read: end of file: iostream error

**Comment by tawmaz** [comment]
Here is the tracking ticket for this issue: 
https://github.com/pocketnetteam/pocketnet.core/issues/76

Please close as duplicate.
