### ISSUE TITLE
Node incompatibility: V0.19.19 node and V0.20.11 node are not doing much communicating.

### ISSUE THREAD

**Issue by the-real-vortex-v** [pocketnetteam/pocketnet.core#95]
I'm running a V0.19.19 node on a windows pc. It happily talks to and gets headers and syncs up (rather quickly) with other nodes on the network. This node has ports forwarded properly from outside to inside etc.

I'm also running a V0.20.11 node on a linux box. It doesn't seem to be communicating with the other v0.19.19 node beyond a handshake. It's connected for a few hrs at a time and they only seem to send/receive a few hundred kilobytes. The V0.20.11 node is about 5k blocks behind the v0.19.19 node. The V0.20.11 node has about 70% cpu free and the network throughput is really low. There is no way this is a disk issue as it will update a single block at least every 1 to 3 secs at it's fastest (I'm sure it can go faster than this but I've only really seen it update about 10 to 15 blocks in a min at it's fastest and usually it's around 2 to 5 a min.

This seems really slow. All of the peers time out frequently. Way more frequently than the v0.19.19 node. Are there any commands I can run to see what might be causing the time outs/slow syncing speed?

**Comment by andyoknen** [comment]
@the-real-vortex-v  The first sign of a slowdown in version 0.20 may be a slow HDD. Since 0.20 works with sqlite, which is located on the hard disk, and not in RAM, then after the processor, the speed of working with the disk is a key factor.
