### ISSUE TITLE
SocialConsensus failure at block 414735 feature/sqlite 20.12

### ISSUE THREAD

**Issue by tawmaz** [pocketnetteam/pocketnet.core#98]
I have reproduced this issue on two systems (Windows + Linux) building from feature/sqlite branch at git commit 78fb244cd0a8775287b9ed7a1c0f535e9d80c67f.

It appears to be a double subscribe issue based on information I have collected from the social consensus validation using gdb:
Block: 414735
Block Hash: f9dde29b4b92b0312651b98aa3293c4577c904cfdf217e4fcebfa24b1ab3b189
Result:SocialConsensusResult_DoubleSubscribe (8)
TX hash: "a98aa7df032c16c57efe153b8d916de6b0882e192bd6d25ab09ac982e3079aba"
Action: ACTION_SUBSCRIBE_PRIVATE

OS: ubunto 20.04 and Windows 10

**Comment by tawmaz** [comment]
This is another transaction in the same block which also does not have a checkpoint:
TX hash: "ac7ddefa0efb21606014f0ffe5bdaa890da9dd59c59922c51d0eb72582ecb0c9"
Code: 8
Type: 303

**Comment by tawmaz** [comment]
Another transaction on the same block:
TX hash: "7fdcd94e189ff9829ccf8dca264f7b5577c2b7d52faa283ecea3917ec112e0ca"
Code: 8
Type: 303

**Comment by tawmaz** [comment]
There are quite a few ACTION_SUBSCRIBE_PRIVATE transactions in this block which fail as duplicate:
TX hash: "d7ab57b7dbcc5383b38ab6dd5e1f7e7daa622e715f85d1648638168b6d7f8703"

TX hash: “bb2676fb51c5e4a9004197245beb104d84ab205696292e47ad69d90f5d90a303"

TX hash: "7bcace22ba0b3db12c70f16a9802fab0122a2b2505f69f9f6128a50a1ffb650e"

TX hash: “87e7606e8d4a15d3dd2e014f9b738d9477bda02b57fd2ba8ac887fcad272951b"

TX hash "8d502590ac91a3abb454cabeb5f8c3bbde2533d3c84278115d4daba00b392f26"

TX hash: "c54642c4a955070b93faf39c3de0fef9da69875694872a6106c41a45f52e7657"

TX hash: "888e18c0f95e9fe1d1ed808c4bfe2bddaef31e7d7614c8223e548ff691790b87"

TX hash: "efee870fcb4042ed963fd337e3d7fe353d5dfa5e66dc7bbdcff7e3df8a4de7ca"

TX hash: "c3c8d1a7dc7039c8bf2a3388de3766b601b42a55270d60e179788a4bf9f3a3b2"

**Comment by graebeerd** [comment]
I can find none of these errors in my debug.log, it's current and has been steady since the release of 20.12, Window 11

**Comment by tawmaz** [comment]
Did you download a checkpoint or perform a complete re-sync of the block chain?  This is only seen during a re-sync.

**Comment by tawmaz** [comment]
Same error with TxType 303 cod 8 on block 414741, block 71c00e0e8e7aa1cca480e05f6c81ae62a979a20626f03982642efad610ac2a20 with these transactions:
bad8541da87f08d59d6241cbc538a902a27f8baa5b0d1095b36d3d37d987daf6
a798427f74abdc0a839fab679db597bb84919746004a82932c0c049620294ef9

**Comment by tawmaz** [comment]
Block 419212 TxType 303 code 8 errors:
a33e591dc0b8918a9781f95bbe42719da91f9bebb82b716f7ffb4082507e901d
9536d7bd5132b3994ef47a70371674517c6f5c1e4c4000890c90412ac4ec10e4
9b7b1049b6de44416b879691bd0dbb5bb4c6352cde2747d625f82e664c08f1ba

Block 419212:
fa3dd182ad1dc287b14a9fbceb8c33ccd8b894e8f2187d8eeef0ed5efb77bec9

**Comment by tawmaz** [comment]
I created a fix of the checkpoint/main.sqlite file here: https://github.com/tawmaz/pocketnet.core/commit/e79eb6fb96ed025bf04c5bf1a98a3e6be9d6592f

I will submit a pull request once I am able to sync both my nodes past block 419213.

**Comment by tawmaz** [comment]
https://github.com/pocketnetteam/pocketnet.core/pull/99

**Comment by graebeerd** [comment]
> Did you download a checkpoint or perform a complete re-sync of the block chain? This is only seen during a re-sync.

I did not but for the last several hours (as I slept) it has been stuck on this:

2021-12-06T14:28:06Z ERROR: ProcessNewBlock: ActivateBestChain failed ( (code 0))
2021-12-06T14:28:06Z WARNING: SocialConsensus validating failed with result 8 for block e5183462a19f0bf2e7265d0bcd9fab2c84c874a1d27b4318f60188dcbd332093
2021-12-06T14:28:06Z ERROR: ConnectTip: ConnectBlock e5183462a19f0bf2e7265d0bcd9fab2c84c874a1d27b4318f60188dcbd332093 failed,  (code 0)

**Comment by andyoknen** [comment]
> > Did you download a checkpoint or perform a complete re-sync of the block chain? This is only seen during a re-sync.
> 
> I did not but for the last several hours (as I slept) it has been stuck on this:
> 
> 2021-12-06T14:28:06Z ERROR: ProcessNewBlock: ActivateBestChain failed ( (code 0)) 2021-12-06T14:28:06Z WARNING: SocialConsensus validating failed with result 8 for block e5183462a19f0bf2e7265d0bcd9fab2c84c874a1d27b4318f60188dcbd332093 2021-12-06T14:28:06Z ERROR: ConnectTip: ConnectBlock e5183462a19f0bf2e7265d0bcd9fab2c84c874a1d27b4318f60188dcbd332093 failed, (code 0)

Please upgrade to version 0.20.13 with update `checkpoints/main.sqlite3` from release page

**Comment by andyoknen** [comment]
Solutions to the described problems are included in https://github.com/pocketnetteam/pocketnet.core/releases/tag/alpha-0.20.13
